### ISSUE TITLE
Remote SSH repositories

### ISSUE THREAD

**Issue by witten** [b3vis/docker-borgmatic#1]
Author of borgmatic here. This is super cool! I want to use it. However, I create backups with borgmatic and Borg to repositories on a remote host via SSH, instead of a local repository that can be conveniently mounted into a container.

So consider this a feature request for your Docker container to support SSH repositories. I'm not that familiar with Alpine, but I think all you may need to do is apk install "openssh-client", and then document how to mount an "~/.ssh/" volume into a container so that passwordless SSH will work when cron runs borgmatic automatically. I'm happy to beta test this if you like.

For background, here are the Borg docs on remote SSH repositories: https://borgbackup.readthedocs.io/en/stable/usage/general.html#repository-urls

**Comment by b3vis** [comment]
Good Afternoon Dan,

Firstly, thank you for your fantastic work with borgmatic. I was fumbling around with a silly shell script for ages before I found your repo.

You’re absolutely right, adding in ‘openssh-client’ should do the trick. I have noticed some other Borg containers also install sshfs which I have added which installs openssl-client as a dependancy.

I’ve just pushed an update to my repo for this which should trigger a rebuild on the Docker Hub.

Please let me know how you get on.

Kind regards,
b3vis

**Comment by witten** [comment]
Awesome, thanks for doing this so quickly! I'll give it a shot. Note that you have "sshfs" twice in the apk upgrade command. Looks like it was already there prior to this change.

**Comment by b3vis** [comment]
So I did… well that’s embarrasing! I’ve just removed the duplicate and pushed it to GitHub. It needed the linux-headers package adding anyway as something had changed and Borg was no longer building.

**Comment by witten** [comment]
This appears to be working out just fine in testing! I'm using Docker Compose, and here's the configuration I'm using to make use of your container:

```
version: '3'

services:
    backup:
        image: b3vis/borgmatic
        hostname: "${NODE_NAME}-calendar-server"
        volumes:
            - /my/source:/source:ro
            - /root/.ssh:/root/.ssh:ro
            - /etc/borgmatic:/config
            - /var/cache/borg:/cache
        environment:
            BORG_PASSPHRASE: "${BORG_PASSPHRASE}"
```

Pretty neat!
