### ISSUE TITLE
Can't find borg cache after container restart. Warning: Attempting to access a previously unknown unencrypted repository

### ISSUE THREAD

**Issue by pr0totyp** [b3vis/docker-borgmatic#34]
After restarting the container borgmatic can't find the borg cache. When running the borgmatic command it gets stuck with `Warning: Attempting to access a previously unknown unencrypted repository`.

The cache and repo folder are mounted to the right mount points and I also specified the standard borg cache location(/root/.cache/borg/) in the borgmatic config file.

After manually allowing the use of the `unknown unencrypted repository` it works on the next run without a problem but after restarting the container the error is coming back at some point.

I also checked the repo id and the id in the cache folder and both match.

docker-compose.yml entrie
```
  web_file_backup:
    image: b3vis/borgmatic
    env_file: .env
    volumes: 
      - ./borgbackup/config.yml:/etc/borgmatic.d/config.yml
      - ./borgbackup/crontab.txt:/etc/borgmatic.d/crontab.txt
      - /srv/web/public/:/mnt/source/:ro
      - /srv/web/log/:/log/
      - /srv/web/backup/borg_repo:/mnt/borg-repository
      - /srv/web/backup/borg_cache:/root/.cache/borg
```
config.yml
```
location:                                                                                                                                                                                                                                                                                                                               
    source_directories:                                                                                                                                                                               
        - /mnt/source/system                                                                                                                                                    
    repositories:
        - /mnt/borg-repository
storage:
    borg_cache_directory: /root/.cache/borg/
    archive_name_format: 'web-{now}'

retention:
    keep_daily: 14
    keep_weekly: 4
    keep_monthly: 12
    keep_yearly: 1
    prefix: 'web-'

consistency:
    checks:
        - repository
        - archives

    prefix: 'web-'
hooks:
    before_backup:
        - echo "`date` - Starting a backup job."
    after_backup:
        - echo "`date` - Backup created."
   on_error:
        - echo "`date` - Error while creating a backup.
```
crontab.txt
```
1 0 * * * PATH=$PATH:/usr/bin /usr/bin/borgmatic -c /etc/borgmatic.d/config.yml --stats  -v 1 2>&1 | tee /log/BorgBackup.log
```
