### ISSUE TITLE
Backup hangs on start

### ISSUE THREAD

**Issue by maxiride** [b3vis/docker-borgmatic#64]
I've deployed the base image and made a test config, to check that everything was fine I entered the container and manually started a backup, however, it hangs on startup and the backup seems to never begin. The source folder contains roughly 1GB of files (pretty small) and the destination is a newly initialized repo from the container itself.

Is this an issue with the image or I should seek support from borg\borgmatic itself?

```
 # borg init -e none /mnt/borg-repository/
/ # ls /mnt/borg-repository/
README       config       data         hints.1      index.1      integrity.1
/ # PATH=$PATH:/usr/bin /usr/bin/borgmatic --stats -v 0 2>&1
Starting a backup job.
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
Deleted data:                    0 B                  0 B                  0 B
All archives:                    0 B                  0 B                  0 B

                       Unique chunks         Total chunks
Chunk index:                       0                    0
------------------------------------------------------------------------------
```

```yml
location:
    source_directories:
        - /mnt/source
    repositories:
        - /mnt/borg-repository
    one_file_system: true

storage:
    compression: lz4
    archive_name_format: 'backup-{now}'

retention:
    keep_hourly: 2
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 3
    prefix: 'backup-'

consistency:
    checks:
        - repository
        - archives
    check_last: 3
    prefix: 'backup-'

hooks:
    before_backup:
        - echo "Starting a backup job."
    after_backup:
        - echo "Backup created."
    on_error:
        - echo "Error while creating a backup."
```
