### ISSUE TITLE
Restoring archive ?

### ISSUE THREAD

**Issue by Kayoku** [b3vis/docker-borgmatic#71]
Hi,

First, thank you for this project !

I'm sorry because it's not really an issue but i'm stuck when I try to do a restoration from a backup and I don't really know where to ask for this... (it's probably a silly question coming from a misunderstanding on my part)
 
For restoring, as said in the README, I run this `docker-compose -f docker-compose.yml -f docker-compose.restore.yml run borgmatic`, then I can extract or mount my archive for restoring. But in practice, when I configure my docker-compose.yml I mount volumes that I want to backup in "ReadOnly", so I can't modify/restoring file here. So my question is... What is the good practice to restoring files when the volume are in RO ?

Thanks...

**Comment by bb** [comment]
You could add a r/w volume in docker-compose.restore.yml. The example below added two lines at the bottom anything you copy from your mounted backup to /restore will end up in the restore directory next to your docker-compose file.

```
version: '3'
services:
  borgmatic:
    container_name: borg-restore

    cap_add:
      - SYS_ADMIN

    security_opt:
      - apparmor:unconfined
      - label:disable

    devices:
      - /dev/fuse:/dev/fuse

    command: /bin/sh

    volumes:
      - ./restore:/restore
```

@b3vis I think this issue can be closed with this explanation.
