### ISSUE TITLE
Prune doesn't working across containers

### ISSUE THREAD

**Issue by derekslenk** [b3vis/docker-borgmatic#76]
Whenever I do a docker-compose down and then an up again, the docker container gets a random hostname internally. 

This is causing the prune command that is run to be: borg prune --keep-daily 7 --keep-weekly 4 --keep-monthly 6 --prefix {hostname}- --remote-path borg1 --debug --show-rc user@my.user.rsync.net:mailcow

Since it is passing hostname to the prune, it is not catching most previous items that need to be pruned if they were created with a different container of borgmatic.

Attaching image of the different archive names that are being created and then not being pruned
![image](https://user-images.githubusercontent.com/42957/126057644-e2c9bd62-5fde-49a2-9f94-e901fd46fbd4.png)

**Comment by MarkJonas** [comment]
If you use the [docker-compose.yml](https://github.com/b3vis/docker-borgmatic/blob/master/base/docker-compose.yml) from this project the container's name should be `borgmatic`. The line `container_name: borgmatic` should ensure this.

**Comment by derekslenk** [comment]
I do have a name (using as part of mailcow) but I explicitly set a new name. It is using the ephemeral container id, not the name:

```
ec97fcfc1fa6-2021-07-18T11:14:09.879672 Sun, 2021-07-18 11:14:11 [6f8e2ffd0b63adad92f3a885e36e0ad457aabf97d1b94cb334123e06f2434005]
4147f56b1917-2021-07-18T13:14:09.442698 Sun, 2021-07-18 13:14:11 [370f31722a921f51980f4d5cd3bda692e3cd52b7c7b82f10fd73e614a49eb30e]
4147f56b1917-2021-07-18T14:14:10.165271 Sun, 2021-07-18 14:14:11 [9d87dd0cd00de9e952f377b60ede292fa511f03f7257c85620c2491b9de71cdf]
root@box:/opt/mailcow-dockerized# docker ps | grep borg
4147f56b1917   b3vis/borgmatic          "/entry.sh"              3 hours ago    Up 3 hours                                                                                                                                                                                                                                        borgmatic
```

**Comment by MarkJonas** [comment]
Well, this leaves me puzzled. I am a user of docker-compose but not with this Borgmatic container. So it won't be of help showing what I am doing.

Alternative proposal: What about removing `{hostname}` from `storage: archive_name_format`, `retention: prefix`, `consitency: prefix`in your *config.yaml*?

**Comment by derekslenk** [comment]
I was really hoping that hostname was set somewhere in the config, but I don't see it :(

```
location:
    source_directories:
        - /mnt/source
    repositories:
        - user@user.rsync.net:mailcow
    remote_path: borg1

retention:
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 6

hooks:
    mysql_databases:
        - name: mail
          username: ausername
          password: nopasswordforyou
          options: --default-character-set=utf8mb4
`````
